/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AtcApplication = IDL.Record({
  'applicantName' : IDL.Text,
  'previousRoles' : IDL.Text,
  'preferredPosition' : IDL.Text,
  'experience' : IDL.Text,
  'availability' : IDL.Text,
  'motivation' : IDL.Text,
  'discordUsername' : IDL.Text,
  'robloxUsername' : IDL.Text,
  'understandingOfAtcProcedures' : IDL.Text,
});
export const CabinCrewApplication = IDL.Record({
  'applicantName' : IDL.Text,
  'previousRoles' : IDL.Text,
  'trainingReceived' : IDL.Text,
  'languages' : IDL.Text,
  'customerServiceSkills' : IDL.Text,
  'experience' : IDL.Text,
  'availability' : IDL.Text,
  'motivation' : IDL.Text,
  'discordUsername' : IDL.Text,
  'robloxUsername' : IDL.Text,
});
export const Flight = IDL.Record({
  'destination' : IDL.Text,
  'arrivalTime' : Time,
  'flightNumber' : IDL.Text,
  'departureTime' : Time,
  'origin' : IDL.Text,
  'aircraftType' : IDL.Text,
});
export const Reservation = IDL.Record({
  'passengerName' : IDL.Text,
  'discordUsername' : IDL.Text,
  'robloxUsername' : IDL.Text,
  'flightDetails' : Flight,
});
export const FlightStatus = IDL.Record({
  'status' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addFlight' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, Time],
      [],
      [],
    ),
  'authenticate' : IDL.Func([IDL.Text], [], []),
  'getAllAtcApplications' : IDL.Func([], [IDL.Vec(AtcApplication)], ['query']),
  'getAllCabinCrewApplications' : IDL.Func(
      [],
      [IDL.Vec(CabinCrewApplication)],
      ['query'],
    ),
  'getAllFlights' : IDL.Func([], [IDL.Vec(Flight)], ['query']),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getFlightStatus' : IDL.Func([], [IDL.Opt(FlightStatus)], ['query']),
  'saveReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'setFlightStatus' : IDL.Func([IDL.Text], [], []),
  'submitAtcApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'submitCabinCrewApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AtcApplication = IDL.Record({
    'applicantName' : IDL.Text,
    'previousRoles' : IDL.Text,
    'preferredPosition' : IDL.Text,
    'experience' : IDL.Text,
    'availability' : IDL.Text,
    'motivation' : IDL.Text,
    'discordUsername' : IDL.Text,
    'robloxUsername' : IDL.Text,
    'understandingOfAtcProcedures' : IDL.Text,
  });
  const CabinCrewApplication = IDL.Record({
    'applicantName' : IDL.Text,
    'previousRoles' : IDL.Text,
    'trainingReceived' : IDL.Text,
    'languages' : IDL.Text,
    'customerServiceSkills' : IDL.Text,
    'experience' : IDL.Text,
    'availability' : IDL.Text,
    'motivation' : IDL.Text,
    'discordUsername' : IDL.Text,
    'robloxUsername' : IDL.Text,
  });
  const Flight = IDL.Record({
    'destination' : IDL.Text,
    'arrivalTime' : Time,
    'flightNumber' : IDL.Text,
    'departureTime' : Time,
    'origin' : IDL.Text,
    'aircraftType' : IDL.Text,
  });
  const Reservation = IDL.Record({
    'passengerName' : IDL.Text,
    'discordUsername' : IDL.Text,
    'robloxUsername' : IDL.Text,
    'flightDetails' : Flight,
  });
  const FlightStatus = IDL.Record({ 'status' : IDL.Text, 'timestamp' : Time });
  
  return IDL.Service({
    'addFlight' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, Time],
        [],
        [],
      ),
    'authenticate' : IDL.Func([IDL.Text], [], []),
    'getAllAtcApplications' : IDL.Func(
        [],
        [IDL.Vec(AtcApplication)],
        ['query'],
      ),
    'getAllCabinCrewApplications' : IDL.Func(
        [],
        [IDL.Vec(CabinCrewApplication)],
        ['query'],
      ),
    'getAllFlights' : IDL.Func([], [IDL.Vec(Flight)], ['query']),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getFlightStatus' : IDL.Func([], [IDL.Opt(FlightStatus)], ['query']),
    'saveReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setFlightStatus' : IDL.Func([IDL.Text], [], []),
    'submitAtcApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'submitCabinCrewApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };