/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AtcApplication {
  'applicantName' : string,
  'previousRoles' : string,
  'preferredPosition' : string,
  'experience' : string,
  'availability' : string,
  'motivation' : string,
  'discordUsername' : string,
  'robloxUsername' : string,
  'understandingOfAtcProcedures' : string,
}
export interface CabinCrewApplication {
  'applicantName' : string,
  'previousRoles' : string,
  'trainingReceived' : string,
  'languages' : string,
  'customerServiceSkills' : string,
  'experience' : string,
  'availability' : string,
  'motivation' : string,
  'discordUsername' : string,
  'robloxUsername' : string,
}
export interface Flight {
  'destination' : string,
  'arrivalTime' : Time,
  'flightNumber' : string,
  'departureTime' : Time,
  'origin' : string,
  'aircraftType' : string,
}
export interface FlightStatus { 'status' : string, 'timestamp' : Time }
export interface Reservation {
  'passengerName' : string,
  'discordUsername' : string,
  'robloxUsername' : string,
  'flightDetails' : Flight,
}
export type Time = bigint;
export interface _SERVICE {
  'addFlight' : ActorMethod<
    [string, string, string, string, Time, Time],
    undefined
  >,
  'authenticate' : ActorMethod<[string], undefined>,
  'getAllAtcApplications' : ActorMethod<[], Array<AtcApplication>>,
  'getAllCabinCrewApplications' : ActorMethod<[], Array<CabinCrewApplication>>,
  'getAllFlights' : ActorMethod<[], Array<Flight>>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getFlightStatus' : ActorMethod<[], [] | [FlightStatus]>,
  'saveReservation' : ActorMethod<[string, string, string, string], undefined>,
  'setFlightStatus' : ActorMethod<[string], undefined>,
  'submitAtcApplication' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    undefined
  >,
  'submitCabinCrewApplication' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];