/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Reservation {
    passengerName: string;
    discordUsername: string;
    robloxUsername: string;
    flightDetails: Flight;
}
export interface FlightStatus {
    status: string;
    timestamp: Time;
}
export type Time = bigint;
export interface CabinCrewApplication {
    applicantName: string;
    previousRoles: string;
    trainingReceived: string;
    languages: string;
    customerServiceSkills: string;
    experience: string;
    availability: string;
    motivation: string;
    discordUsername: string;
    robloxUsername: string;
}
export interface Flight {
    destination: string;
    arrivalTime: Time;
    flightNumber: string;
    departureTime: Time;
    origin: string;
    aircraftType: string;
}
export interface AtcApplication {
    applicantName: string;
    previousRoles: string;
    preferredPosition: string;
    experience: string;
    availability: string;
    motivation: string;
    discordUsername: string;
    robloxUsername: string;
    understandingOfAtcProcedures: string;
}
export interface backendInterface {
    addFlight(flightNumber: string, origin: string, destination: string, aircraftType: string, departureTime: Time, arrivalTime: Time): Promise<void>;
    authenticate(password: string): Promise<void>;
    getAllAtcApplications(): Promise<Array<AtcApplication>>;
    getAllCabinCrewApplications(): Promise<Array<CabinCrewApplication>>;
    getAllFlights(): Promise<Array<Flight>>;
    getAllReservations(): Promise<Array<Reservation>>;
    getFlightStatus(): Promise<FlightStatus | null>;
    saveReservation(passengerName: string, discordUsername: string, robloxUsername: string, flightNumber: string): Promise<void>;
    setFlightStatus(status: string): Promise<void>;
    submitAtcApplication(applicantName: string, discordUsername: string, robloxUsername: string, experience: string, motivation: string, preferredPosition: string, availability: string, understandingOfAtcProcedures: string, previousRoles: string): Promise<void>;
    submitCabinCrewApplication(applicantName: string, discordUsername: string, robloxUsername: string, experience: string, motivation: string, availability: string, languages: string, previousRoles: string, trainingReceived: string, customerServiceSkills: string): Promise<void>;
}
import type { FlightStatus as _FlightStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFlight(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time, arg5: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFlight(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFlight(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async authenticate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticate(arg0);
            return result;
        }
    }
    async getAllAtcApplications(): Promise<Array<AtcApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAtcApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAtcApplications();
            return result;
        }
    }
    async getAllCabinCrewApplications(): Promise<Array<CabinCrewApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCabinCrewApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCabinCrewApplications();
            return result;
        }
    }
    async getAllFlights(): Promise<Array<Flight>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFlights();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFlights();
            return result;
        }
    }
    async getAllReservations(): Promise<Array<Reservation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReservations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReservations();
            return result;
        }
    }
    async getFlightStatus(): Promise<FlightStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlightStatus();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlightStatus();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveReservation(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReservation(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReservation(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setFlightStatus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFlightStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFlightStatus(arg0);
            return result;
        }
    }
    async submitAtcApplication(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAtcApplication(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAtcApplication(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async submitCabinCrewApplication(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCabinCrewApplication(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCabinCrewApplication(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FlightStatus]): FlightStatus | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
